### PR TITLE
Amended partition validation to fails if contains '.' as dot-notation isn't supported. Closes #214

### LINKED ISSUE #214: Issue: `. notation` Not Supported for `filter` Parameter in Tailpipe Config
#### Description  
Tailpipe allows log collection based on the `filter` parameter configured in the Tailpipe config. When using **arrow notation** (`->>`), the logs are successfully collected. However, when using **dot notation** (`.`) for filtering nested object keys, an error occurs.

###### **Config:**
```hcl
partition "aws_waf_traffic_log" "my_logs_write" {
  filter = "(http_request ->> 'httpMethod') not like 'GET'"

  source "aws_s3_bucket" {
    connection = connection.aws.nagraj
    bucket     = "aws-waf-logs-my-tp-log"
  }
}
```

###### **Result:**
```
tailpipe collect aws_waf_traffic_log.my_logs_write --from 2025-02-01

Collecting logs for aws_waf_traffic_log.my_logs_write from 2025-02-01 

Artifacts:
  Discovered: 14 
  Downloaded: 14 27kB
  Extracted:  14 

Rows:
  Received: 357 
  Enriched: 357 
  Saved:    139 
  Filtered: 218 

Files:
  Compacted: 2 => 2

Completed: 8s
```

###### **Config:**
```hcl
partition "aws_waf_traffic_log" "my_logs_write" {
  filter = "http_request.httpMethod not like 'GET'"

  source "aws_s3_bucket" {
    connection = connection.aws.nagraj
    bucket     = "aws-waf-logs-my-tp-log"
  }
}
```

###### **Result:**
```
tailpipe collect aws_waf_traffic_log.my_logs_write --from 2025-02-01

Collecting logs for aws_waf_traffic_log.my_logs_write from 2025-02-01 

Artifacts:
  Discovered: 14 
  Downloaded: 14 27kB
  Extracted:  14 

Rows:
  Received: 357 
  Enriched: 357 
  Saved:      0 

Completed: 7s
Error: collection error: execution failed: execution in error state: job group 1739809301958 has errors: failed to convert file /Users/parthasarathi/.tailpipe/internal/collection/default/46672/source/1739809301958-1.jsonl: failed to export data to parquet: Binder Error: Referenced table "http_request" not found!
Candidate tables: "read_ndjson"
LINE 85: 	) WHERE http_request.httpMethod not like 'GET' AND tp_timestamp >= '2025-02-01T00:00:00') TO '/Users/parthasarathi/.tailpipe/data/default' (FORMAT PARQUET, PARTITION_BY (tp_table,tp_partition,tp_index,tp_date), OVERWRITE_OR_IGNORE, FILENAME_PATTERN "data_20250217215151_176527_{i}");
```

#### Expected Behavior  
Both **arrow notation** (`->>`) and **dot notation** (`.`) should work interchangeably in the `filter` parameter for querying nested JSON keys.

### PR DESCRIPTION
**Pull request by graza-io**
Closes #214

### CODE REVIEW

**Comment by graza-io** [comment]
```
Error: Internal Error: Failed to decode all config files: Filter contains dot notation: Partition aws_waf_traffic_log.test contains '.' in filter, dot-notation is currently unsupported, please use arrow-notation instead (field->>'sub_field' != 'value').
```

File: internal/config/partition.go [hunk 1]
```diff
@@ -136,6 +136,15 @@ func (c *Partition) Validate() hcl.Diagnostics {
 				})
 			}
 		}
+
+		// check for `.` (dot notation) as we currently don't support this as structs aren't compiled at this stage
+		if strings.Contains(c.Filter, ".") {
+			diags = append(diags, &hcl.Diagnostic{
```
Comment (kaidaguerre) [inline internal/config/partition.go:142]: I think:
```diags = append(diags, &hcl.Diagnostic{
				Severity: hcl.DiagError,
				Summary:  fmt.Sprintf("Partition %s contains invalid filter", c.GetUnqualifiedName())
				Detail:  "dot-notation is currently unsupported in partition filters, please use arrow-notation instead (field->>'sub_field' != 'value').",
			})

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
